Add docs: Deploy deployment into a specified set of target clusters
karmada-io/karmada pull request #1231
Opened 2022-01-10 07:47 UTC by XiShanYongYe-Chang

Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Add docs: Deploy deployment into a specified set of target clusters.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-01-10 08:11 UTC, XiShanYongYe-Chang commented
Hi @Tingtal, can you help review it?

2022-01-10 13:08 UTC, Tingtal requested changes

2022-01-10 13:08 UTC, Tingtal commented on docs/userguide/resource-propagating.md
> +`.spec.placement.clusterAffinity` field of PropagationPolicy represents scheduling restrictions to a certain set of clusters. If not set, any cluster can be scheduling candidate.
```suggestion
`.spec.placement.clusterAffinity` field of PropagationPolicy represents scheduling restrictions on a certain set of clusters, without which any cluster can be scheduling candidates.
```

2022-01-10 13:08 UTC, Tingtal commented on docs/userguide/resource-propagating.md
> +LabelSelector is a filter to select member clusters by labels, it uses `*metav1.LabelSelector` type. If non-nil and non-empty, only the clusters match this filter will be selected.
```suggestion
LabelSelector is a filter to select member clusters by labels. It uses `*metav1.LabelSelector` type. If it is non-nil and non-empty, only the clusters match this filter will be selected.
```

2022-01-10 13:08 UTC, Tingtal commented on docs/userguide/resource-propagating.md
> +FieldSelector is a filter to select member clusters by fields. If non-nil and non-empty, only the clusters match this filter will be selected.
```suggestion
FieldSelector is a filter to select member clusters by fields. If it is non-nil and non-empty, only the clusters match this filter will be selected.
```

2022-01-10 13:08 UTC, Tingtal commented on docs/userguide/resource-propagating.md
> +The `key` value in `matchExpressions` field now support three values: `provider`, `region`, `zone`, which correspond to the `.spec.provider`, `.spec.region`, `.spec.zone` fields of the Cluster object
```suggestion
The `key` in `matchExpressions` now supports `provider`, `region`, and `zone`, which correspond to the `.spec.provider`, `.spec.region`, and `.spec.zone` fields of the Cluster object, respectively.
```

2022-01-10 13:08 UTC, Tingtal commented on docs/userguide/resource-propagating.md
> +The `operator` value in `matchExpressions` field now support two operator: `In` and `NotIn`.
```suggestion
The `operator` in `matchExpressions` now supports `In` and `NotIn`.
```

2022-01-10 13:08 UTC, Tingtal commented on docs/userguide/resource-propagating.md
> +User can set the ClusterNames field to specify the name of the selected cluster list.
```suggestion
Users can set the `ClusterNames` field to specify the selected clusters.
```

2022-01-10 13:08 UTC, Tingtal commented on docs/userguide/resource-propagating.md
> +User can set the ExcludeClusters fields to specify the cluster name list, indicating that these clusters are ignored.
```suggestion
User can set the `ExcludeClusters` fields to specify the clusters to be ignored.
```

2022-01-11 01:34 UTC, XiShanYongYe-Chang commented
@Tingtal, thanks for your review.

2022-01-11 09:39 UTC, RainbowMango reviewed
/lgtm
/approve

2022-01-11 09:40 UTC, merged