Complete missing step for working-with-anp
karmada-io/karmada pull request #1241
Opened 2022-01-11 12:55 UTC by XiShanYongYe-Chang

Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Complete missing step for `working-with-anp.md`. After deploying ANP, we need to add command flags `cluster-api-endpoint` and `proxy-server-address` for karmada-agent deployment.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2022-01-11 13:03 UTC, XiShanYongYe-Chang commented
/cc @Tingtal

Hi, can you help review it?

2022-01-12 01:54 UTC, RainbowMango commented on docs/working-with-anp.md
> +After deploying ANP deployment, we need to add command flags `cluster-api-endpoint` and `proxy-server-address` for karmada-agent deployment on `member3` cluster.
```suggestion
After deployed ANP deployment, we need to add extra command flags `--cluster-api-endpoint` and `--proxy-server-address` for `karmada-agent` deployment on `member3` cluster.
```

2022-01-12 02:06 UTC, XiShanYongYe-Chang commented on docs/working-with-anp.md
> +After deploying ANP deployment, we need to add command flags `cluster-api-endpoint` and `proxy-server-address` for karmada-agent deployment on `member3` cluster.
Thanks, I have updated it.

2022-01-12 11:34 UTC, Tingtal requested changes

2022-01-12 11:34 UTC, Tingtal commented on docs/working-with-anp.md
> +After deployed ANP deployment, we need to add extra command flags `--cluster-api-endpoint` and `--proxy-server-address` for `karmada-agent` deployment on `member3` cluster.
```suggestion
After deploying the ANP deployment, we need to add extra command flags `--cluster-api-endpoint` and `--proxy-server-address` for `karmada-agent` deployment in `member3` cluster.
```

2022-01-12 11:34 UTC, Tingtal commented on docs/working-with-anp.md
> +Port `8088` is set by our code modification in ANP: https://github.com/mrlihanbo/apiserver-network-proxy/blob/v0.0.24/dev/cmd/server/app/server.go#L267, you can also modify it to a different value.
```suggestion
Port `8088` is set by our code modification in ANP: https://github.com/mrlihanbo/apiserver-network-proxy/blob/v0.0.24/dev/cmd/server/app/server.go#L267. You can also modify it to a different value.
```

2022-01-13 01:19 UTC, XiShanYongYe-Chang commented
@Tingtal thanks for you review :)

2022-01-13 01:38 UTC, RainbowMango commented on docs/working-with-anp.md
> +Where `cluster-api-endpoint` is the APIEndpoint of the cluster. You can obtain it from the KubeConfig file of the `member3` cluster.
```suggestion
Where `--cluster-api-endpoint` is the APIEndpoint of the cluster. You can obtain it from the KubeConfig file of the `member3` cluster. 
```
Add `--` to all flags.

2022-01-13 01:48 UTC, RainbowMango approved these changes
/lgtm
/approve

2022-01-13 02:16 UTC, merged