Add resource interpreter document
karmada-io/karmada pull request #1282
Opened 2022-01-19 12:35 UTC by RainbowMango

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Added `CustomResourceInterpreter` document.

**Which issue(s) this PR fixes**:
Fixes #1250

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2022-01-19 12:35 UTC, RainbowMango commented
@Tingtal Could you please help take a look?

2022-01-20 02:39 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +as normal resources, therefore, the advanced scheduling algorithms cannot be used for them.
```suggestion
as normal resources. Therefore, the advanced scheduling algorithms cannot be used for them.
```

2022-01-20 03:40 UTC, Tingtal requested changes

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +- customized interpreter: Used to interpreter custom resources or override the built-in interpreters.
```suggestion
- customized interpreter: interprets custom resources or overrides the built-in interpreters.
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +> Note: The main difference between `built-in` and `customized` interpreter is the `built-in` interpreted is
```suggestion
> Note: The major difference between `built-in` and `customized` interpreters is that the `built-in` interpreter is 
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +> implemented and maintained by Karmada community, it will be built into Karmada components, such as
```suggestion
> implemented and maintained by Karmada community and will be built into Karmada components, such as 
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +> `karmada-controller-manager`. On the contrary, the `customized` interpreter is implemented and maintained by users,
```suggestion
> `karmada-controller-manager`. On the contrary, the `customized` interpreter is implemented and maintained by users.
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +> it should be registered to Karmada as an `Interpreter Webhook`(See below for more details).
```suggestion
> It should be registered to Karmada as an `Interpreter Webhook` (see below for more details).
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +When interpreting resource, we usually to extract multiple pieces of information from it, the `Interpreter Operations`
```suggestion
When interpreting resources, we often get multiple pieces of information extracted. The `Interpreter Operations`
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +> Note: Not all the designed operations are supported(See below for supported operations).
```suggestion
> Note: Not all the designed operations are supported (see below for supported operations).
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +> and the `customized` interpreter has higher priority than `built-in` interpreter if they both interpreting the same
```suggestion
> and the `customized` interpreter has higher priority than `built-in` interpreter if they are both interpreting the same 
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +> For example, the `built-in` interpreter serves `InterpretReplica` for `Deployment` with version `apps/v1`, if there
```suggestion
> For example, the `built-in` interpreter serves `InterpretReplica` for `Deployment` with version `apps/v1`. If there 
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +> is a customized interpreter registered to Karmada for interpreting the same resource, the `customized` interpreter win and the
```suggestion
> is a customized interpreter registered to Karmada for interpreting the same resource, the `customized` interpreter wins and the 
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +For the common Kubernetes native or well-known extended resources, the interpreter operations are built-in, that means
```suggestion
For the common Kubernetes native or well-known extended resources, the interpreter operations are built-in, which means
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +the users usually don't need to implement the customized interpreter. If you want more resources should be built-in,
```suggestion
the users usually don't need to implement customized interpreters. If you want more resources to be built-in,
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +## Customize Interpreter
```suggestion
## Customized Interpreter
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +The customized interpreter is implemented and maintained by users, it developed as extensions and
```suggestion
A customized interpreter is implemented and maintained by users, developed as an extension and 
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +run as webhooks at runtime.
```suggestion
running as a webhook at runtime.
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +Karmada components(such as `karmada-controller-manager`), and sends back its decision as an
```suggestion
Karmada components (such as `karmada-controller-manager`), and sends back its decision as an 
```

2022-01-20 03:40 UTC, Tingtal commented on docs/userguide/customizing-resource-interpreter.md
> +You can configure what resources and supported operations are subject to what interpreter webhook
```suggestion
You can configure which resources and supported operations are subject to which interpreter webhook 
```

2022-01-20 11:24 UTC, merged