Add documents about controllers inherited from kubernetes.
karmada-io/karmada pull request #1558
Opened 2022-03-29 08:46 UTC by RainbowMango

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR set up the documentation about the controller we inherited from Kubernetes.
And takes the `serviceaccount-token` controller as a start.

**Which issue(s) this PR fixes**:
Fixes #655 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

2022-03-29 08:47 UTC, RainbowMango commented
/assign @Tingtal @Garrybest

2022-03-29 08:47 UTC, RainbowMango commented
cc @mrlihanbo @GitHubxsy

2022-03-29 08:54 UTC, mrlihanbo commented
/lgtm

2022-03-29 12:40 UTC, Garrybest commented
/lgtm
By the way, this doc happens to help me know more about tokens controller. Thanks!

2022-03-29 12:41 UTC, XiShanYongYe-Chang reviewed
/lgtm

2022-03-29 12:43 UTC, RainbowMango commented
Thanks, guys. Let's wait for @Tingtal for the grammar check.

2022-03-30 08:41 UTC, Tingtal requested changes

2022-03-30 08:41 UTC, Tingtal commented on docs/userguide/configure-controllers.md
> +  - [Kubernetes controllers](#kubernetes-controllers)
```suggestion
  - [Kubernetes Controllers](#kubernetes-controllers)
```

2022-03-30 08:41 UTC, Tingtal commented on docs/userguide/configure-controllers.md
> +    - [Recommended controllers](#recommended-controllers)
```suggestion
    - [Recommended Controllers](#recommended-controllers)
```

2022-03-30 08:41 UTC, Tingtal commented on docs/userguide/configure-controllers.md
> +Following controllers are tested and recommended by Karmada.
```suggestion
The following controllers are tested and recommended by Karmada.
```

2022-03-30 08:41 UTC, Tingtal commented on docs/userguide/configure-controllers.md
> +The `serviceaccount-token` controller runs as part of `kube-controller-manager`, one of its responsibility is
```suggestion
The `serviceaccount-token` controller runs as part of `kube-controller-manager`.
```

2022-03-30 08:41 UTC, Tingtal commented on docs/userguide/configure-controllers.md
> +it watches `ServiceAccount` creation and creates a corresponding ServiceAccount token Secret to allow API access.
```suggestion
It watches `ServiceAccount` creation and creates a corresponding ServiceAccount token Secret to allow API access.
```

2022-03-30 08:41 UTC, Tingtal commented on docs/userguide/configure-controllers.md
>  > Note: The default controller list might be changed in the following release. The controllers enabled by last release
```suggestion
> Note: The default controller list might be changed in the future releases. The controllers enabled in the last release
```

2022-03-30 08:41 UTC, Tingtal commented on docs/userguide/configure-controllers.md
> +Karmada by other tools, you might have to configure the controllers by `--controllers` flag just like what we did in
```suggestion
Karmada using other tools, you might have to configure the controllers by `--controllers` flag just like what we did in
```

2022-03-30 10:34 UTC, merged