[Docs]: Add Propagate Dependencies user guide
karmada-io/karmada pull request #1684
Opened 2022-04-28 15:19 UTC by hanweisen

Signed-off-by: hanweisen <hanweisen_yewu@cmss.chinamobile.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add Propagate Dependencies user guide
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-04-28 15:32 UTC, hanweisen commented
This feature only supports propagate ConfigMap and Secret , I'm curious why it is not supported Service and PVC.

2022-04-29 01:26 UTC, XiShanYongYe-Chang commented
/cc @mrlihanbo

2022-04-29 01:42 UTC, RainbowMango commented
> This feature only supports propagate ConfigMap and Secret , I'm curious why it is not supported Service and PVC.

The `ConfigMap` and `Secret` are just a start because it's easier to implement. The door is open for other dependencies, we can iterate it one by one.

2022-04-29 01:43 UTC, RainbowMango commented
cc @Tingtal Could you please help with it?
Looks pretty good to me.

2022-05-05 09:06 UTC, Tingtal requested changes

2022-05-05 09:06 UTC, Tingtal commented on docs/userguide/propagate-dependencies.md
> +Deployment, Job, Pod, DaemonSet and StatefulSet dependencies(ConfigMaps and Secrets) can be propagated to the member
```suggestion
Deployment, Job, Pod, DaemonSet and StatefulSet dependencies (ConfigMaps and Secrets) can be propagated to member
```

2022-05-05 09:06 UTC, Tingtal commented on docs/userguide/propagate-dependencies.md
> +clusters automatically. This document demonstrates how to use this feature. More design details please referring to
```suggestion
clusters automatically. This document demonstrates how to use this feature. For more design details, please refer to
```

2022-05-05 09:06 UTC, Tingtal commented on docs/userguide/propagate-dependencies.md
> +After apply them. Deployment and ConfigMap are properly propagated to member cluster.
```suggestion
Upon successful policy execution, the Deployment and ConfigMap are properly propagated to the member cluster.
```

2022-05-05 09:09 UTC, Tingtal commented
> cc @Tingtal Could you please help with it? Looks pretty good to me.

@RainbowMango Hi! Language checked. Just a few small touches.

2022-05-05 12:19 UTC, RainbowMango commented
Please help squash the commits.

2022-05-05 12:25 UTC, hanweisen commented
Thanks a lot @Tingtal. These commit has been squashed @RainbowMango

2022-05-05 12:26 UTC, hanweisen commented
Thanks a lot @Tingtal. These commit has been squashed @RainbowMango

2022-05-05 13:03 UTC, RainbowMango commented
/lgtm
/approve

2022-05-05 13:33 UTC, merged