Add application proposal for Karmada
karmada-io/karmada pull request #2309
Opened 2022-08-02 07:22 UTC by Poor12

Signed-off-by: Poor12 <shentiecheng@huawei.com>

**What type of PR is this?**
/kind design
/kind documentation

**What this PR does / why we need it**:
Add application proposal for Karmada to enable users to manage multi-cluster applications in Karmada.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
cc@RainbowMango

**Does this PR introduce a user-facing change?**:

2022-08-04 02:07 UTC, Fish-pro commented
@Poor12 I would like to ask you why the multi-cluster application does not include the PropagationPolicy and OverridePolicy, how to consider this, are there any more learning documents about application?

2022-08-04 04:08 UTC, Poor12 commented
> @Poor12I would like to ask you why the multi-cluster application does not include the PropagationPolicy and OverridePolicy, how is this considered? Is there more documentation about the application that I can learn?

Application is more like workloads with more complex organizational forms. I'm more inclined to follow karmada's way of dealing with kubernetes objects. This feature is still on design. We can discuss on the community meeting soon.

2022-08-05 04:08 UTC, Tingtal requested changes
Small touches on the language. Pls check.

2022-08-05 04:08 UTC, Tingtal commented on docs/proposals/application/README.md
> +	// Info contains human readable key,value pairs for the Application.
```suggestion
	// Info contains human readable key-value pairs for the Application.
```

2022-08-05 04:08 UTC, Tingtal commented on docs/proposals/application/README.md
> +	// Links are a list of descriptive URLs intended to be used to surface additional documentation, dashboards, etc.
```suggestion
	// Links is a list of descriptive URLs intended for surfacing additional documentation, dashboards, etc.
```

2022-08-05 04:08 UTC, Tingtal commented on docs/proposals/application/README.md
> +	// (optional) The mine type of the image (e.g., "image/png").
Should be "mime" type?

2022-08-05 04:08 UTC, Tingtal commented on docs/proposals/application/README.md
> +// InfoItem is a human readable key,value pair containing important information about how to access the Application.
```suggestion
// InfoItem is a human readable key-value pair containing important information about how to access the Application.
```

2022-08-05 04:08 UTC, Tingtal commented on docs/proposals/application/README.md
> +- Unit Test covering.
Not sure what "covering" means here.
In my opinion, "Unit tests" is enough. Pls check.

2022-08-05 04:08 UTC, Tingtal commented on docs/proposals/application/README.md
> +- E2E covering.
E2E coverage?

2022-08-08 08:51 UTC, closed without merging

2022-08-09 01:52 UTC, nuclearwu commented
> > @Poor12I would like to ask you why the multi-cluster application does not include the PropagationPolicy and OverridePolicy, how is this considered? Is there more documentation about the application that I can learn?
> 
> Application is more like workloads with more complex organizational forms. I'm more inclined to follow karmada's way of dealing with kubernetes objects. This feature is still on design. We can discuss on the community meeting soon.

At present, application distribution mainly includes two scenarios for us, one is to deploy differentiated applications in different clusters, and the other is to distribute Kubernetes resources in applications containing multiple workloads to different clusters. So I wonder if karmada will support both? Also, can we get involved together?

2022-08-10 09:09 UTC, Poor12 commented
Hi, @nuclearwu, Application is a budding idea. We actually want to listen more users's voice. If you have any demands or ideas, welcome to talk about it in our slack channel or wechat group.