move docs to karmada website
karmada-io/karmada pull request #2323
Opened 2022-08-04 06:53 UTC by Poor12

Signed-off-by: Poor12 <shentiecheng@huawei.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Remove docs to website.

**Which issue(s) this PR fixes**:
Fixes #2316 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
None

2022-08-05 02:49 UTC, Tingtal requested changes
One small touch on the language. Pls check. Thanks.

2022-08-05 02:49 UTC, Tingtal commented on docs/README.md
> +All documentations for the Karmada is hosted at [karmada-io/website](https://github.com/karmada-io/website).
```suggestion
Karmada documentation is all hosted on [karmada-io/website](https://github.com/karmada-io/website).
```

2022-08-05 06:30 UTC, Poor12 commented on docs/README.md
> +All documentations for the Karmada is hosted at [karmada-io/website](https://github.com/karmada-io/website).
Done.

2022-08-08 08:21 UTC, Poor12 commented
cc @RainbowMango

2022-08-08 08:28 UTC, merged