fix deploy-scheduler-estimator.sh cannot generate correct kubeconfig file problem
karmada-io/karmada pull request #2482
Opened 2022-09-07 10:46 UTC by cmicat

fix deploy-scheduler-estimator.sh cannot generate correct kubeconfig file problem

Signed-off-by: raymondmiaochaoyue <raymondmiaochaoyue@didichuxing.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

When used as [Cluster Accurate Scheduler Estimator For Rescheduling](https://karmada.io/docs/userguide/scheduling/scheduler-estimator) guided, the original `hack/deploy-scheduler-estimator.sh` have two problems:

(1) The <MEMBER_CLUSTER_KUBECONFIG> file is not flattened, and the `kubectl create secret generic` command will copy the <MEMBER_CLUSTER_KUBECONFIG> file's content directly without changing anything. So if the <MEMBER_CLUSTER_KUBECONFIG> contains none embedded cert reference like the following, karmada-scheduler-estimator will not be able to read the certificate file. Because the certificate file is not mounted by the container.

```
client-certificate: /home/raymondmiaochaoyue/.minikube/profiles/ray-karmada-member2/client.crt
```

(2) <MEMBER_CLUSTER_KUBECONFIG> is used as secret's content, it will not be changed by `--context=` parameter in `kubectl create secret generic` command. We need change it first, then save to temporary file.

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2022-09-07 11:09 UTC, ikaven1024 requested changes

2022-09-07 11:09 UTC, ikaven1024 commented on hack/deploy-scheduler-estimator.sh
> +MEMBER_CLUSTER_KUBECONFIG_NAME=$(basename ${MEMBER_CLUSTER_KUBECONFIG})
```suggestion
MEMBER_CLUSTER_KUBECONFIG_NAME=$(basename "${MEMBER_CLUSTER_KUBECONFIG}")
```

2022-09-07 11:10 UTC, ikaven1024 commented
/assign

2022-09-07 11:41 UTC, cmicat commented on hack/deploy-scheduler-estimator.sh
> +MEMBER_CLUSTER_KUBECONFIG_NAME=$(basename ${MEMBER_CLUSTER_KUBECONFIG})
> fixed

2022-09-08 02:47 UTC, ikaven1024 commented
/lgtm

2022-09-08 06:10 UTC, RainbowMango commented
/assign
Thanks in advance. I'll look at it tomorrow.

2022-09-09 03:28 UTC, RainbowMango approved these changes
Fantastic!!!
Thanks for doing this.

I don't know these flags before.
```
    --flatten=false:
	Flatten the resulting kubeconfig file into self-contained output (useful for creating portable kubeconfig
	files)
    --minify=false:
	Remove all information not used by current-context from the output
```

/lgtm
/approve

2022-09-09 03:29 UTC, merged