scheduler & descheduler introduce scheduler-estimator-service-prefix flag
karmada-io/karmada pull request #2527
Opened 2022-09-17 11:46 UTC by carlory

Signed-off-by: carlory <baofa.fan@daocloud.io>

**What type of PR is this?**

/kind feature

**Which issue(s) this PR fixes**:
Part of #2526 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
scheduler & descheduler introduce scheduler-estimator-service-prefix flag
```

2022-09-17 15:16 UTC, carlory commented
/cc @Garrybest @RainbowMango

2022-09-18 08:51 UTC, Garrybest requested changes
You could delete the constant `estimatorServicePrefix` in `names.go`.

2022-09-18 09:22 UTC, carlory commented
@Garrybest 

`estimatorServicePrefix` is also used by `karmadactl addon` command.

I will fill an another pr to resolve it. 

https://github.com/karmada-io/karmada/blob/acd746980e9700abc1743b41d20289c9fcc84746/pkg/util/names/names.go#L113

https://github.com/karmada-io/karmada/blob/acd746980e9700abc1743b41d20289c9fcc84746/pkg/karmadactl/addons/estimator/estimator.go#L36

2022-09-19 03:53 UTC, Garrybest commented
/lgtm

2022-09-19 15:13 UTC, carlory commented
/assign @rainbowmango

2022-10-13 05:49 UTC, carlory commented
/cc @RainbowMango @Garrybest

2022-10-13 06:31 UTC, Garrybest commented
/lgtm

2022-10-15 06:36 UTC, RainbowMango approved these changes
/approve

2022-10-15 06:37 UTC, merged