Fix: remove the setTransitionTime from cluster status controller.
karmada-io/karmada pull request #3316
Opened 2023-03-22 07:23 UTC by xigang

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

There is no need to call setTransitionTime before calling the SetStatusCondition method. From the code logic, call setTransitionTime is not required.

**Which issue(s) this PR fixes**:
Fixes #https://github.com/karmada-io/karmada/issues/3313

**Special notes for your reviewer**:

/cc @XiShanYongYe-Chang 

**Does this PR introduce a user-facing change?**:
```
NONE
```

2023-03-22 08:00 UTC, Poor12 reviewed
Could you delete `setTransitionTime` together? Seems this function is non-used.

2023-03-22 08:32 UTC, xigang commented
> Could you delete `setTransitionTime` together? Seems this function is non-used.

`setTransitionTime` has been deleted

2023-03-22 08:50 UTC, RainbowMango reviewed
Can you have a test on it to see if the condition transition time is set as expected?

It should be ok, but one more test would be better.

2023-03-22 08:54 UTC, XiShanYongYe-Chang reviewed
Thanks~
/lgtm

2023-03-22 09:55 UTC, XiShanYongYe-Chang commented
Have you make a test on your local site?

2023-03-22 11:07 UTC, xigang commented
> Have you made a test on your local site?

I add some unit test cases

> Have you made a test on your local site?
I'll add some unit test cases a little later.

2023-03-23 01:17 UTC, XiShanYongYe-Chang commented
Hi, @xigang thanks for your work. I think we don't need to add ut to the method in the third-party library, but judging from your new ut context, what @RainbowMango says is satisfied.

Can you help remove the newly added ut, and we can continue to approve?

2023-03-23 01:50 UTC, RainbowMango requested changes
Sorry, I didn't make it clear.

> Can you have a test on it to see if the condition transition time is set as expected?

I mean we can test it manually would be fine.  No worries, I can help do it.
But, please remove the unit test.

2023-03-23 01:50 UTC, RainbowMango commented on pkg/util/condition_test.go
> +			meta.SetStatusCondition(tt.ouputConditions, tt.inputCondition)
We don't need this unit test, as this function is maintained by Kubernetes and there is already a unit test at:
https://github.com/kubernetes/kubernetes/blob/d2be69ac11346d2a0fab8c3c168c4255db99c56f/staging/src/k8s.io/apimachinery/pkg/api/meta/conditions_test.go#L27

2023-03-23 02:00 UTC, xigang commented
@XiShanYongYe-Chang @RainbowMango The newly added unit tests have been removed. I only have the local environment, can you help verify it in your test environment?

2023-03-23 02:09 UTC, RainbowMango approved these changes
It works. Thanks.
/lgtm
/approve

Ready condition:
```yaml
  - lastTransitionTime: "2023-03-23T02:01:33Z"
    message: cluster is healthy and ready to accept workloads
    reason: ClusterReady
    status: "True"
    type: Ready
```

Not Ready condition:
```yaml
  - lastTransitionTime: "2023-03-23T02:06:53Z" ## We can see the transitionTime is updated as expected.
    message: cluster is not reachable
    reason: ClusterNotReachable
    status: "False"
    type: Ready
```

2023-03-23 02:54 UTC, merged

2023-03-23 03:12 UTC, xigang commented
> It works. Thanks. /lgtm /approve
> 
> Ready condition:
> 
> ```yaml
>   - lastTransitionTime: "2023-03-23T02:01:33Z"
>     message: cluster is healthy and ready to accept workloads
>     reason: ClusterReady
>     status: "True"
>     type: Ready
> ```
> 
> Not Ready condition:
> 
> ```yaml
>   - lastTransitionTime: "2023-03-23T02:06:53Z" ## We can see the transitionTime is updated as expected.
>     message: cluster is not reachable
>     reason: ClusterNotReachable
>     status: "False"
>     type: Ready
> ```

@RainbowMango  Thanks for helping verify.