add e2e of imageoverride
karmada-io/karmada pull request #379
Opened 2021-05-27 04:20 UTC by XiShanYongYe-Chang

**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

add e2e of imageoverride with https://github.com/karmada-io/karmada/pull/370

```
SSS
------------------------------
[OverridePolicy] apply overriders testing Deployment imageOverride with empty predicate test 
  deployment imageOverride testing
  /root/karmada/test/e2e/overridepolicy_test.go:61
STEP: creating propagationPolicy(karmadatest-nm6/deploy-xr4)
STEP: creating overridePolicy(karmadatest-nm6/deploy-xr4)
STEP: creating deployment(karmadatest-nm6/deploy-xr4)
STEP: check if deployment present on member clusters have correct image value
I0527 12:18:46.108427   22970 overridepolicy_test.go:74] Waiting for deployment(karmadatest-nm6/deploy-xr4) present on cluster(member1)
I0527 12:18:51.112567   22970 overridepolicy_test.go:74] Waiting for deployment(karmadatest-nm6/deploy-xr4) present on cluster(member2)
STEP: removing deployment(karmadatest-nm6/deploy-xr4)
STEP: removing overridePolicy(karmadatest-nm6/deploy-xr4)
STEP: removing propagationPolicy(karmadatest-nm6/deploy-xr4)

• [SLOW TEST:10.067 seconds]
[OverridePolicy] apply overriders testing
/root/karmada/test/e2e/overridepolicy_test.go:20
  Deployment imageOverride with empty predicate test
  /root/karmada/test/e2e/overridepolicy_test.go:21
    deployment imageOverride testing
    /root/karmada/test/e2e/overridepolicy_test.go:61
------------------------------
[OverridePolicy] apply overriders testing Pod imageOverride test 
  pod imageOverride testing
  /root/karmada/test/e2e/overridepolicy_test.go:145
STEP: creating propagationPolicy(karmadatest-nm6/pod-bsf)
STEP: creating overridePolicy(karmadatest-nm6/pod-bsf)
STEP: creating pod(karmadatest-nm6/pod-bsf)
STEP: check if pod present on member clusters have correct image value
I0527 12:18:56.163858   22970 overridepolicy_test.go:158] Waiting for pod(karmadatest-nm6/pod-bsf) present on cluster(member1)
I0527 12:19:01.167646   22970 overridepolicy_test.go:158] Waiting for pod(karmadatest-nm6/pod-bsf) present on cluster(member2)
STEP: removing pod(karmadatest-nm6/pod-bsf)
STEP: removing overridePolicy(karmadatest-nm6/pod-bsf)
STEP: removing propagationPolicy(karmadatest-nm6/pod-bsf)

• [SLOW TEST:10.055 seconds]
[OverridePolicy] apply overriders testing
/root/karmada/test/e2e/overridepolicy_test.go:20
  Pod imageOverride test
  /root/karmada/test/e2e/overridepolicy_test.go:105
    pod imageOverride testing
    /root/karmada/test/e2e/overridepolicy_test.go:145
------------------------------
[OverridePolicy] apply overriders testing Deployment imageOverride with predicate test 
  deployment imageOverride testing
  /root/karmada/test/e2e/overridepolicy_test.go:230
STEP: creating propagationPolicy(karmadatest-nm6/deploy-rpv)
STEP: creating overridePolicy(karmadatest-nm6/deploy-rpv)
STEP: creating deployment(karmadatest-nm6/deploy-rpv)
STEP: check if deployment present on member clusters have correct image value
I0527 12:19:06.198839   22970 overridepolicy_test.go:243] Waiting for deployment(karmadatest-nm6/deploy-rpv) present on cluster(member1)
I0527 12:19:11.202521   22970 overridepolicy_test.go:243] Waiting for deployment(karmadatest-nm6/deploy-rpv) present on cluster(member2)
STEP: removing deployment(karmadatest-nm6/deploy-rpv)
STEP: removing overridePolicy(karmadatest-nm6/deploy-rpv)
STEP: removing propagationPolicy(karmadatest-nm6/deploy-rpv)

• [SLOW TEST:10.035 seconds]
[OverridePolicy] apply overriders testing
/root/karmada/test/e2e/overridepolicy_test.go:20
  Deployment imageOverride with predicate test
  /root/karmada/test/e2e/overridepolicy_test.go:190
    deployment imageOverride testing
    /root/karmada/test/e2e/overridepolicy_test.go:230
------------------------------
SSSSSSSSSSSSS
Ran 3 of 19 Specs in 38.398 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 16 Skipped
PASS
```

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2021-05-27 07:03 UTC, RainbowMango requested changes

2021-05-27 07:03 UTC, RainbowMango commented on test/e2e/overridepolicy_test.go
> +	ginkgo.Context("Deployment imageOverride with empty predicate test", func() {
The deployment in this case only has one container, the coverage is not enough.

2021-05-27 07:03 UTC, RainbowMango commented on test/e2e/overridepolicy_test.go
> +	ginkgo.Context("Deployment imageOverride with predicate test", func() {
Same as above.
```suggestion
	ginkgo.Context("Deployment override specific images in container list", func() {
```

2021-05-27 09:50 UTC, XiShanYongYe-Chang commented on test/e2e/overridepolicy_test.go
> +					gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
Thanks! I've modified it.

2021-05-27 09:59 UTC, XiShanYongYe-Chang commented on test/e2e/overridepolicy_test.go
> +	ginkgo.Context("Deployment imageOverride with empty predicate test", func() {
Done. I've modified NewPod function.

2021-05-28 06:45 UTC, RainbowMango approved these changes

2021-05-28 06:46 UTC, merged