standardize the naming of karmada config in karmadactl method
karmada-io/karmada pull request #5797
Opened 2024-11-09 11:56 UTC by chaosi-zju

**What type of PR is this?**

/kind feature
/kind cleanup

**What this PR does / why we need it**:

In karmada, here are two important secrets, which is mount by most karmada components. One is karmada-cert, which contains a series of cert files like ca.crt, apiserver.crt and so on; another is karmada-kubeconfig, which contains a kubeconfig of karmada-apiserver.

However, in different installation methods, we used inconsistent secret naming or file path naming, which can potentially cause some unnecessary problems, detail refer to https://github.com/karmada-io/karmada/issues/5363.

This PR aims to standardize the naming of karmada config in `karmadactl` installation method.

**Which issue(s) this PR fixes**:

Fixes part of #6051

**Special notes for your reviewer**:

karmada-agent is a bit different, this PR doesn't include the rename of karmada-agent

**Does this PR introduce a user-facing change?**:

```release-note
`karmadactl`: standardize the naming of karmada config in karmadactl installation method
```

2025-01-16 12:06 UTC, chaosi-zju commented
PR is ready, @RainbowMango 

---

latest test report:

```shell
$ kubectl get secret -n karmada-system
NAME                                  TYPE     DATA   AGE
etcd-cert                             Opaque   4      2m40s
karmada-aggregated-apiserver-config   Opaque   1      2m40s
karmada-cert                          Opaque   16     2m40s
karmada-controller-manager-config     Opaque   1      2m40s
karmada-descheduler-config            Opaque   1      2m40s
karmada-metrics-adapter-config        Opaque   1      2m40s
karmada-scheduler-config              Opaque   1      2m40s
karmada-search-config                 Opaque   1      2m40s
karmada-webhook-cert                  Opaque   2      2m40s
karmada-webhook-config                Opaque   1      2m40s
kube-controller-manager-config        Opaque   1      2m40s
member4-kubeconfig                    Opaque   1      42s

$ kubectl get pods -n karmada-system         
NAME                                                   READY   STATUS    RESTARTS   AGE
etcd-0                                                 1/1     Running   0          2m11s
karmada-aggregated-apiserver-cd487bf7b-fgz44           1/1     Running   0          95s
karmada-apiserver-5c58546979-9fvsg                     1/1     Running   0          2m8s
karmada-controller-manager-d6b65f748-wcj9q             1/1     Running   0          88s
karmada-descheduler-65d9d48fdb-sj4pn                   1/1     Running   0          18s
karmada-metrics-adapter-665444967b-qndkw               1/1     Running   0          27s
karmada-scheduler-765dcfbddf-crnxj                     1/1     Running   0          89s
karmada-scheduler-estimator-member4-86c6568998-gllzz   1/1     Running   0          14s
karmada-search-fd9f84555-zk6cx                         1/1     Running   0          21s
karmada-webhook-75fd7b67db-x8q6k                       1/1     Running   0          87s
kube-controller-manager-58646bb75d-6kskd               1/1     Running   0          90s
```

2025-01-17 01:45 UTC, RainbowMango commented
OK. will do

2025-01-24 09:07 UTC, RainbowMango reviewed
/assign

2025-01-24 09:59 UTC, RainbowMango requested changes

2025-01-24 09:59 UTC, RainbowMango commented on pkg/karmadactl/addons/init/enable_option.go
> +}
```suggestion
func getEnablingAddons(addonNames []string) map[string]*Addon {
	var enablingAddons = map[string]*Addon{}
	
	for _, name := range addonNames {
		if name == "all" {
			enablingAddons = Addons
			break
		}
		if addon := Addons[name]; addon != nil {
			enablingAddons[name] = addon
		}
	}

	return enablingAddons
}
```

2025-01-24 09:59 UTC, RainbowMango commented on pkg/karmadactl/cmdinit/options/global.go
> +}
This is shared by both `addon` and `init`, why not put it to package `pkg/karmadactl/util`?

2025-01-24 09:59 UTC, RainbowMango commented on pkg/karmadactl/cmdinit/options/global.go
> +	KarmadaConfigSecretSuffix = "-config" //nolint:gosec
Only one place requiring this const? Why not hardcode it?

2025-01-24 09:59 UTC, RainbowMango commented on pkg/karmadactl/cmdinit/options/global.go
> +	KarmadaConfigFieldName = "karmada.config" //nolint:gosec
Explain why there is a gosec warning?

2025-01-24 10:02 UTC, chaosi-zju commented on pkg/karmadactl/addons/init/enable_option.go
> +}
so, the key point is renaming `item` to `name`?

2025-01-24 10:43 UTC, chaosi-zju commented
comments fixed and retest ok

2025-01-26 02:18 UTC, RainbowMango approved these changes
/lgtm
/approve

2025-01-26 02:18 UTC, merged