reflect status of job/service/ingress to resource template
karmada-io/karmada pull request #609
Opened 2021-08-16 12:25 UTC by mrlihanbo

Signed-off-by: lihanbo <lihanbo2@huawei.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
reflect status of job/service/ingress to resource template

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
aggregate status of load balance service:
```
spec:
  clusterIP: 10.100.245.74
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31963
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: member1
      ip: 192.0.2.127
```

aggregate status of job"
```status:
  conditions:
  - lastProbeTime: "2021-08-16T11:06:39Z"
    lastTransitionTime: "2021-08-16T11:06:39Z"
    message: Job executed failed in some member clusters
    reason: JobFailed
    status: "True"
    type: Failed
  failed: 6
  succeeded: 8

```

```status:
  conditions:
  - lastProbeTime: "2021-08-16T11:27:01Z"
    lastTransitionTime: "2021-08-16T11:27:01Z"
    message: Job completed
    reason: Completed
    status: "True"
    type: Complete
  succeeded: 12

```

**Does this PR introduce a user-facing change?**:
“NONE”

2021-08-16 13:17 UTC, RainbowMango commented
You might want to add an E2E test for each of them.

2021-08-17 02:07 UTC, mrlihanbo commented
> You might want to add an E2E test for each of them.

I can add e2e of agregating job status and ingress propagation, but I can't add the e2e of agregating service and ingress status due to kind clusters do not have lb controller and ingress controller.

2021-08-18 09:07 UTC, RainbowMango requested changes

2021-08-18 09:07 UTC, RainbowMango commented on pkg/util/detector/aggregate_status.go
> +	}
```suggestion
```
This will block us from updating the status.

2021-08-18 11:17 UTC, RainbowMango commented
/lgtm
/approve

2021-08-18 11:17 UTC, merged