add issue template of question
karmada-io/karmada pull request #673
Opened 2021-08-28 05:30 UTC by lonelyCZ

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add issue template of question.

**Which issue(s) this PR fixes**:
Fixes #671 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

2021-08-28 07:43 UTC, pigletfly requested changes

2021-08-28 07:43 UTC, pigletfly commented on .github/ISSUE_TEMPLATE/question.md
> +- Karmada version:
should we provide k8s version as well?

2021-08-28 08:34 UTC, lonelyCZ commented on .github/ISSUE_TEMPLATE/question.md
> +- Karmada version:
> should we provide k8s version as well?

yes

2021-08-30 06:35 UTC, RainbowMango commented on .github/ISSUE_TEMPLATE/question.md
> +**Anything else we need to know?**:
Same with the `kind/bug` template? I don't think so.

2021-09-06 07:16 UTC, RainbowMango commented on .github/ISSUE_TEMPLATE/question.md
> +<!-- Please use this template while providing as much info as possible. Thanks!-->
```suggestion
<!-- Please use this template while asking a new question. Thanks!
Please make sure you have read the FAQ and searched the issue list.
- FAQ: https://github.com/karmada-io/karmada/blob/master/docs/frequently-asked-questions.md
- Issues: https://github.com/karmada-io/karmada/issues?q=is%3Aissue+
-->
```

2021-09-06 07:16 UTC, RainbowMango commented on .github/ISSUE_TEMPLATE/question.md
> +
I suggest removing this item.

2021-09-06 09:10 UTC, XiShanYongYe-Chang commented
hi, @lonelyCZ , please squash you commit.

2021-09-08 02:18 UTC, RainbowMango commented
Yeah. Squash your commit to one will be all set. Thanks.

2021-09-08 02:31 UTC, lonelyCZ reviewed
> Yeah. Squash your commit to one will be all set. Thanks.

Ok, I try to solve it immediately.

2021-09-08 07:11 UTC, closed without merging

2021-09-08 07:37 UTC, XiShanYongYe-Chang commented
@lonelyCZ  Why close this MR?

2021-09-08 07:39 UTC, RainbowMango commented
Do you need help?

2021-09-08 07:55 UTC, lonelyCZ commented
@RainbowMango @XiShanYongYe-Chang 
I just trid to squash commits, but there are some conflicts. Then I delete the branch and want to recreate it.

I need learn how to squash commits correctly.

2021-09-08 08:10 UTC, RainbowMango commented
I guess you have messed your branch. So, my suggestion would be :
- Copy `.github/ISSUE_TEMPLATE/question.md ` locally
- Remove the branch `lonelyCZ-patch-1` from your workspace and your forked repo.
- git checkout -b lonelyCZ-patch-1
- Copy `.github/ISSUE_TEMPLATE/question.md ` back
- git commit -s -m "xxx"
- git push origin lonelyCZ-patch-1 -f

2021-09-08 08:14 UTC, lonelyCZ commented
@RainbowMango  Thank you, I try it now.

2021-09-08 09:10 UTC, lonelyCZ commented
@RainbowMango 
I can`t reopen this pr, should I recreate a pr?

2021-09-08 09:23 UTC, RainbowMango commented
Yes, that'll be much easier.

2021-09-08 09:49 UTC, lonelyCZ commented
@RainbowMango @XiShanYongYe-Chang @pigletfly 

Thank you very much. I have more knowledge to learn.